(define-library (srfi 64 execution)
  (import
   (scheme base)
   (scheme case-lambda)
   (scheme complex)
   (scheme eval)
   (scheme read)
   (srfi 1)
   (srfi 35)
   (srfi 48)
   (srfi 64 test-runner)
   (srfi 64 source-info))
  (include-library-declarations "execution.exports.sld")
  (include "execution.body.scm"))
